# Camera
PRODUCT_PROPERTY_OVERRIDES += \
	persist.bokeh.switch.lux=290 \
	persist.camera.auxswitch.threshold=330 \
	persist.camera.imglib.usefdlite=1 \
	persist.camera.depth.focus.cb=0 \
	persist.camera.expose.aux=1 \
	persist.camera.isp.clock.optmz=0 \
	persist.camera.isp.turbo=1 \
	persist.camera.linkpreview=0 \
	persist.camera.mainswitch.threshold=419 \
	persist.camera.set.afd=4 \
	persist.camera.stats.test=0 \
	persist.flash.low.lux=390 \
	persist.flash.light.lux=340 \
	persist.sys.exif.make=Xiaomi \
	persist.radio.VT_CAM_INTERFACE=2 \
	ro.eyecare.brightness.threshold=3 \
	ro.eyecare.brightness.level=8 \
	ro.hist.brightness.threshold=5 \
	persist.vendor.camera.multicam.hwsync=TRUE \
	persist.vendor.camera.multicam.fpsmatch=TRUE \
	persist.vendor.camera.enableAdvanceFeatures=0x347 \
	persist.vendor.camera.display.umax=1920x1080 \
	persist.vendor.camera.display.lmax=1280x720 \
	vidc.enc.dcvs.extra-buff-count=2 \
	persist.vendor.camera.expose.aux=1 \
	persist.vendor.camera.preview.ubwc=0 \
	persist.vendor.camera.stats.test=0 \
	persist.vendor.camera.isp.clock.optmz=0 \
	persist.vendor.camera.linkpreview=0 \
	persist.vendor.camera.isp.turbo=1 \
	persist.vendor.camera.awb.sync=2 \
	persist.vendor.camera.fdvideo=1 \
	persist.vendor.camera.mfnrframenum=8 \
	persist.vendor.camera.multicam=TRUE \
	persist.vendor.camera.multicam.framesync=1 \
	persist.vendor.camera.auxswitch.threshold=330 \
	persist.vendor.camera.mainswitch.threshold=419 \
	persist.vendor.camera.stats.test=5 \
	persist.vendor.camera.depth.focus.cb=0 \
	persist.vendor.camera.imglib.usefdlite=1 \
	persist.vendor.bokeh.switch.lux=290 \
	persist.vendor.camera.exif.make=Xiaomi \
	persist.vendor.camera.HAL3.enabled=1 \
	vendor.camera.aux.packagelist=com.android.camera

# Display
PRODUCT_PROPERTY_OVERRIDES += \
    ro.sf.blurs_are_expensive=1 \
    ro.surface_flinger.supports_background_blur=0
